openapi: 3.0.0
info:
  title: GPT Intake Action
  version: 1.0.0
paths:
  /logPhase:
    post:
      summary: Log a user's name and favorite MasonrySEO phase
      operationId: logPhase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phase:
                  type: string
      responses:
        "200":
          description: Successful
